### ISSUE TITLE
This bundle works?

### ISSUE THREAD

**Issue by vacho** [Djamy/GoogleCalendarBundle#1]

**Comment by Djamy** [comment]
@vacho It needs tests, documentations and probably some fix but it's a good start to work with google's api.

I should spend more time on this one, you're not the first one to ask..

**Comment by jokari4242** [comment]
Hello!

how to install this bundle?

For this moment, i have downloaded the projet, put in src/Djamy/GoogleCalendarBundle

And in my AppKernel.php : 

new Djamy\GoogleCalendarBundle\DjamyGoogleCalendarBundle();

I'm trying to call the service in a controller like this : 
$this->get('calendar.google')->addEvent('XXX@XX.XX', new \DateTime(),new \DateTime(), 'test', 'test description', array('XXX@XX.XX'));

I have this error : 
You have requested a non-existent service "calendar.google"

Any Idea?

Thanks :-)

**Comment by jokari4242** [comment]
I'm in progress :-) 

1/ Create a api account server to server here : https://console.developers.google.com/apis/api/calendar/overview

2/ Add this in parameters.yml : 

```
google_calendar:
    client_email: XXXX@XXXXXX.iam.gserviceaccount.com
    api_url: https://www.googleapis.com/auth/calendar
    api_key_file: YOUR_P12_FILE
```

3/ I have turn public: true in services.yml, that perfect for calling this in my controller now.

4/ Call the service : $this->container->get('am.calendar_google')->addEvent('primary', $entity->getStart(),$entity->getEnd(), $entity->getTitle(), $entity->getDescription(), array('XXX@XXX.XXX'));
